# Starship command prompt generator configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[shell]
# Since we use multiple shells, to be aware.
disabled = false
nu_indicator = "nu"
fish_indicator = "fish"
zsh_indicator = "zsh"
bash_indicator = "bash"
powershell_indicator = "powershell"
cmd_indicator = "cmd"

[username]
# Always display user name
show_always = true
format = '[$user]($style)'
style_user = 'bold white'
style_root = 'bold red'

[hostname]
# Always display host name
ssh_only = false
format = '@[$ssh_symbol$hostname]($style): '

[time]
# We do want timestamps for our commands
disabled = false
format = "[$time]($style) "
