# Starship command prompt generator configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[shell]
# Since we use multiple shells, to be aware.
disabled = false
nu_indicator = "nu"
fish_indicator = "fish"
zsh_indicator = "zsh"
bash_indicator = "bash"
powershell_indicator = "powershell"
cmd_indicator = "cmd"
style = "gray"

[username]
# Always display user name
show_always = true
format = '[$user]($style)'
style_user = 'bold green'
style_root = 'bold red'

[hostname]
# Always display host name
ssh_only = false
format = '@[$ssh_symbol$hostname]($style): '
style = 'bold purple'

[directory]
style = 'bold cyan'
repo_root_style = 'bold yellow'
before_repo_root_style = 'bold cyan'
truncation_symbol = '.../'
truncation_length = 0
truncate_to_repo = false
# fish_style_pwd_dir_length = 1

[git_branch]
style = 'bold yellow'

[time]
# We do want timestamps for our commands
disabled = false
format = "[$time]($style) "
style = "bold white"
