# Starship command prompt generator configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# The default timeout of 500ms is sometimes insufficient for git status operations
command_timeout = 5000

# `format` defines the overall prompt. Use components like $all, $username, $hostname, $directory, etc.
# TODO: how do we insert an OSC 133 marker here without breaking the parser?
format = '''
$fill
=== $all'''

[fill]
symbol = '_'
style = 'bold black'

[shell]
# Since we use multiple shells, to be aware.
disabled = false
nu_indicator = "nu"
fish_indicator = "fish"
zsh_indicator = "zsh"
bash_indicator = "bash"
powershell_indicator = "powershell"
cmd_indicator = "cmd"
style = "gray"

[status]
# Display the exit code of the last command, if it was non-zero.
disabled = false
format = '[$symbol $status]($style) '
style = 'bold red'

[memory_usage]
disabled = false
threshold = 75

[username]
# Always display user name
show_always = true
format = '[$user]($style)'
style_user = 'bold green'
style_root = 'bold red'

[hostname]
# Always display host name
ssh_only = false
format = '@[$ssh_symbol$hostname]($style): '
style = 'bold purple'

[localip]
disabled = false
ssh_only = true
format = '[$localipv4]($style) '
style = 'bold blue'

[os]
disabled = false

[directory]
style = 'bold cyan'
repo_root_style = 'bold yellow'
before_repo_root_style = 'bold cyan'
truncation_symbol = '.../'
truncation_length = 0
truncate_to_repo = false
# fish_style_pwd_dir_length = 1

[git_branch]
style = 'bold yellow'

[time]
# We do want timestamps for our commands
disabled = false
format = "[$time]($style) "
style = "bold white"

[character]
success_symbol = '[=>](bold green)'
error_symbol = '[=>](bold red)'
vimcmd_symbol = '[N:](bold cyan)'
vimcmd_visual_symbol = '[V:](bold yellow)'
vimcmd_replace_symbol = '[R:](bold purple)'
vimcmd_replace_one_symbol = '[r:](bold purple)'
