# Starship command prompt generator configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[shell]
# Since we use multiple shells, to be aware.
disabled = false

[username]
# Always display user name
show_always = true

[hostname]
# Always display host name
ssh_only = false

[time]
# We do want timestamps for our commands
disabled = false
format = "[$time]($style) "
