# Starship command prompt generator configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[time]
# We do want timestamps for our commands
disabled = false
format = "[$time]($style) "
