#!/usr/bin/env bash
# A script to perform NixOS system rebuild using currently cached nixpkgs copy (normal mode of stock nixos-rebuild).
#
# Usage:
#   nixos-rebuild-current-nixpkgs <standard nixos-rebuild arguments...>

# set -x  # Uncomment to trace command invocations for debugging
# set -e  # Abort on unchecked error exit codes
# set -u  # Treat referencing unset variables and parameters as errors
set -o pipefail  # For pipelines: "return status is the value of the last (rightmost) command to exit with a non-zero status"

log() {
  echo -e "$@";
}

logError() {
  echo -e "$@" 1>&2;
}

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

SUDO=''
if [ "$EUID" -ne 0 ]; then
    echo "NixOS system rebuild scripts must be run as a superuser -- prepending 'sudo' for you..."
    unset HOME
    SUDO="sudo --preserve-env"
fi

log "Preparing to rebuild NixOS system using current channel configuration..."

TIMESTAMP=$(date "+%Y%m%d-%H%M%S")
DOTFILES_COMMIT_HASH=$(git-last-commit-hash "$SCRIPT_DIR")

# Get current (even if updated with `sudo nix-channel --update`) version/hash commit number to embed
CURRENT_CHANNEL_VERSION=$(nix-instantiate --eval --attr 'lib.version' '<nixpkgs>' | tr -d '"')  # Remove surrounding quote marks from the returned string value

# NIXOS_LABEL env var can be predefined to override the value we auto-compute as a fallback here.
# Note that nixos-version will print this value once the built configuration is booted up.
if [ -z "$NIXOS_LABEL" ]; then
    export NIXOS_LABEL="$TIMESTAMP--dotfiles-$DOTFILES_COMMIT_HASH--nixpkgs-$CURRENT_CHANNEL_VERSION"

    # NIXOS_LABEL_SUFFIX env var is an optional text to append to the generated NixOS label
    if [ -n "$NIXOS_LABEL_SUFFIX" ]; then
        export NIXOS_LABEL="$NIXOS_LABEL--$NIXOS_LABEL_SUFFIX"
    fi
fi

logError "Rebuilding system configuration: $NIXOS_LABEL"

exec $SUDO nixos-rebuild -I nixos-config=/etc/nixos/configuration.nix "$@"
