#!/bin/sh

echo "Killing any running fluidsynth instances..."
pkill fluidsynth
sleep 1

echo "Launching fluidsynth MIDI synthesizer..."
/usr/bin/fluidsynth -a pulseaudio -m alsa_seq -s -i -g 0.7 -R on -C on -r 48000 /usr/share/sounds/sf2/FluidR3_GM.sf2 &
sleep 3

echo "Connecting Keystation MIDI keyboard to fluidsynth MIDI synthesizer..."
aconnect "USB Keystation:0" FLUID:0

echo "Should be connected now. Try playing something..."
