#!/usr/bin/env bash

os=$(uname)

if [ "$os" == "Linux" ]; then
    # FIXME detect if PulseAudio is indeed running, else fall back on ALSA

    # using PulseAudio
    pavucontrol

    # using ALSA
    # alsamixer

elif [ "$os" == "FreeBSD" ]; then
    aumix
elif [ "$os" == "Darwin" ]; then
    open /System/Library/PreferencePanes/Sound.prefPane
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    echo "FIXME Running on MinGW32"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    echo "FIXME Running on MinGW64"
else
    echo "Cannot invoke audio volume control: unknown OS"
fi
