#!/usr/bin/env python3

import subprocess

PREFIX_LENGTH = 20
SUFFIX_LENGTH = 20
SEPARATOR = ".."
ERROR_OUTPUT = "--"

def get_status_information() -> str:
    process = subprocess.run(["mpc"], stdout=subprocess.PIPE)
    return process.stdout.decode().strip().split("\n")[1] if process.returncode == 0 else ERROR_OUTPUT

def get_song_information() -> str:
    process = subprocess.run(["mpc", "-f", "[%title% ][@%name%]", "current"], stdout=subprocess.PIPE)
    output = process.stdout.decode().strip() if process.returncode == 0 else ""

    if (len(output) > PREFIX_LENGTH + SUFFIX_LENGTH + len(SEPARATOR)):
        return output[:PREFIX_LENGTH] + SEPARATOR + output[-SUFFIX_LENGTH:]
    else:
        return output

print((get_song_information() + " " + get_status_information()).strip())
