#!/usr/bin/env bash

os=$(uname)

if [ "$os" == "Linux" ]; then
    # FIXME detect if PulseAudio is indeed running, else fall back on ALSA
    pactl list sinks | egrep 'Mute:|^[[:space:]]Volume:' | sed -e 's/Mute: yes$/×/' -e 's/Mute: no//' -e 's,.* \([0-9][0-9]*%\).*,\1,' | tr -d '\n' | xargs echo -n
elif [ "$os" == "FreeBSD" ]; then
    echo "$(mixer vol | cut -w -f 7-8)%"
elif [ "$os" == "Darwin" ]; then
    echo -n "$(osascript -e 'output muted of (get volume settings)' | sed -e 's/true/×/' -e 's/false//')"
    echo "$(osascript -e 'output volume of (get volume settings)')%"
elif [ "$(expr substr $(uname -s) 1 7)" == "MSYS_NT" ]; then
    echo "--"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    echo "--"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    echo "--"
else
    echo "--"
fi
