#!/bin/sh
# FIXME make it list all displays if no arguments are provided, do the rest otherwise
xrandr | grep -ws connected

MONITOR1=eDP-1
MONITOR2=HDMI-1

xrandr --output $MONITOR1 --off
xrandr --output $MONITOR2 --off

xrandr --output $MONITOR2 --auto --primary
xrandr --output $MONITOR1 --auto --left-of $MONITOR2
